// @ts-check
import { readFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// The config reference's sidebar entries are generated by `make confdocs`
// alongside the pages themselves, so the sidebar keeps the config structs'
// declaration order (Starlight's autogenerate sorts directories first).
const configSidebar = JSON.parse(
	readFileSync(new URL('./config-sidebar.json', import.meta.url), 'utf8'),
);

// Deployed to GitHub Pages, so the site lives under the repository name.
export default defineConfig({
	site: 'https://mnestor.github.io',
	base: '/ssoossh',
	integrations: [
		starlight({
			title: 'ssoossh',
			description: 'Short-lived SSH certificates from your identity provider.',
			// The app's design system, applied to the docs; see
			// frontend/DESIGN.md for the tokens these mirror.
			customCss: ['./src/styles/ssoossh.css'],
			components: {
				// Adds the app's accent eyebrow above the page heading.
				PageTitle: './src/components/PageTitle.astro',
			},
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/mnestor/ssoossh' },
			],
			sidebar: [
				{ label: 'Getting started', slug: 'getting-started' },
				{
					label: 'Guides',
					items: [
						{ label: 'The ssoossh client', slug: 'guides/client' },
						{ label: 'Service accounts', slug: 'guides/service-accounts' },
						{ label: 'sudo with PAM', slug: 'guides/pam-sudo' },
					],
				},
				{
					label: 'Examples',
					items: [{ label: 'Server configurations', slug: 'examples/server-configs' }],
				},
				{
					label: 'Configuration reference',
					items: configSidebar,
				},
			],
		}),
	],
});
