// @ts-check
import { readFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// The config reference's sidebar entries are generated by `make confdocs`
// alongside the pages themselves, so the sidebar keeps the config structs'
// declaration order (Starlight's autogenerate sorts directories first).
const configSidebar = JSON.parse(
	readFileSync(new URL('./config-sidebar.json', import.meta.url), 'utf8'),
);

// Deployed to GitHub Pages, so the site lives under the repository name.
export default defineConfig({
	site: 'https://mnestor.github.io',
	base: '/ssoossh',
	integrations: [
		starlight({
			title: 'ssoossh',
			description: 'Short-lived SSH certificates from your identity provider.',
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/mnestor/ssoossh' },
			],
			sidebar: [
				{ label: 'Getting started', slug: 'getting-started' },
				{
					label: 'Configuration reference',
					items: configSidebar,
				},
			],
		}),
	],
});
