// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// Deployed to GitHub Pages, so the site lives under the repository name.
export default defineConfig({
	site: 'https://mnestor.github.io',
	base: '/ssoossh',
	integrations: [
		starlight({
			title: 'ssoossh',
			description: 'Short-lived SSH certificates from your identity provider.',
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/mnestor/ssoossh' },
			],
			sidebar: [
				{ label: 'Getting started', slug: 'getting-started' },
				{
					label: 'Configuration reference',
					// The pages are generated by `make confdocs`; declaration
					// order is pinned by each page's sidebar.order frontmatter.
					items: [{ autogenerate: { directory: 'reference/config' } }],
				},
			],
		}),
	],
});
