---
version: 2

release:
  prerelease: auto
  draft: false

before:
  hooks:
    - go mod tidy
    # - go generate ./...

# env:
#   - CGO_ENABLED=0
#   - GOFLAGS=-buildvcs=false

builds:
  - id: server-linux-build
    binary: ssoossh-server
    dir: &dirsrv ./cmd/ssoossh-server
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    ldflags: &build-ldflags |
      -X internal.Version={{.Version}}
      -X internal.Commit={{.Commit}}
      -X internal.Date={{.Date}}

  - id: windows-build
    binary: &name "ssoossh"
    dir: &dir ./cmd/ssoossh
    # main: "./cmd/ssoossh/ssoossh.go"
    goos:
      - windows
    goarch:
      - amd64
    ldflags: *build-ldflags

  - id: linux-build
    binary: *name
    dir: *dir
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    ldflags: *build-ldflags

  - id: macos-build
    binary: *name
    dir: *dir
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: *build-ldflags
    hooks:
      post:
        - cmd: downloads/quill sign-and-notarize "{{ .Path }}" --dry-run={{ .IsSnapshot }} --ad-hoc={{ .IsSnapshot }} -vv

  - id: netbsd-build
    dir: *dir
    binary: *name
    goos:
      - netbsd
    goarch:
      - amd64
    ldflags: *build-ldflags

nfpms:
  - id: client
    license: &license "Apache 2.0"
    maintainer: &maintainer "Mike Nestor"
    homepage: &website "https://github.com/mnestor/ssoossh"
    description: &description "client for ssoossh-server to retrieve and manage ssh certificates"
    builds:
      - linux-build
    formats: &nfpmFormats
      - rpm
      - deb
    contents:
      # Basic file that applies to all packagers
      - src: docs/ssoossh.yaml.default
        dst: /etc/ssoossh.yaml
        type: "config|noreplace"

  - id: server
    license: *license
    maintainer: *maintainer
    homepage: *website
    description: &description "server to authorize and sign ssh public keys with a certificate"
    builds:
      - server-linux-build
    formats: *nfpmFormats
    contents:
      # Basic file that applies to all packagers
      - src: docs/ssoossh-serveryaml.default
        dst: /etc/soossh-server.yaml
        type: "config|noreplace"

archives:
  - id: server-archives
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    builds:
      - server-linux-build

  - id: linux-archives
    builds:
      - linux-build

  - id: netbsd-archives
    builds:
      - netbsd-build

  - formats: ["zip"]
    id: windows-archives
    builds:
      - windows-build

  - formats: ["zip"]
    id: macos-archives
    builds:
      - macos-build
