// Command genwirecontract writes docs/wire-contract.json, the versioned
// statement of what ssoosshd puts on the wire.
//
// Why this exists: the HTTP API has a consumer Go cannot check. pam_ssoossh
// (github.com/mnestor/ssoossh-pam) is a separate project written in C, so it
// shares no types with this repository and no compiler sits between the two.
// A renamed JSON tag here regenerates docs/openapi.yaml without complaint,
// passes every gate, and breaks that module in production.
//
// The manifest closes that by making a contract change loud. It records four
// things, each chosen for what it catches:
//
//   - version, incremented automatically whenever anything else below moves.
//     This is the number ssoossh-pam pins, and the thing a reviewer sees.
//   - endpoints, the method and path set from docs/openapi.yaml. Catches an
//     endpoint added, removed or renamed. Read from the paths rather than
//     hashing the whole spec on purpose: editing a handler's prose
//     description should not bump the contract version.
//   - sse_events, the terminal SSE event names. A client must register for
//     every one of them or it blocks forever, so an addition here is a change
//     other implementations have to hear about.
//   - fixtures, a SHA-256 per golden file. These are the actual shapes: the
//     JSON payloads under internal/apitypes/testdata and the raw stream
//     framing under server/controller/testdata. A renamed field moves a hash.
//
// The version bump is automatic rather than something a developer has to
// remember, for the same reason .coverage-floors is a committed file rather
// than a convention: the goal is not to make the change hard, it is to make
// it visible in review and to give the other repository a number to pin.
//
// Usage: genwirecontract [-check | -print-version]
//
// Run it from the repository root; -check exits non-zero if the file would
// change, which is what `make wire-contract-check` asserts. -print-version
// writes the committed version to stdout and nothing else, which is how
// scripts/gen-wire-contract-bundle.sh names what it ships.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/mnestor/ssoossh/internal/apitypes"
)

// manifestPath is the committed artifact. Under docs/ rather than beside the
// fixtures because it describes several trees at once, and because it ships
// as a release asset next to docs/openapi.yaml (see .goreleaser.yml).
const manifestPath = "docs/wire-contract.json"

// specPath is the generated OpenAPI document the endpoint set is read from.
const specPath = "docs/openapi.yaml"

// fixtureGlobs are the golden trees whose contents define the shapes. Both
// are produced by tests (`go test ./internal/apitypes/ -update` and
// `go test ./server/controller/ -update`), so this command only ever reads
// them: it reports what the shapes are, it does not decide them.
var fixtureGlobs = []string{
	"internal/apitypes/testdata/*.json",
	"server/controller/testdata/sse_stream_*.sse",
}

// manifest is docs/wire-contract.json's shape. Field order here is the field
// order in the file, so a human opening it reads the version first.
type manifest struct {
	// Version increments whenever any other field changes. ssoossh-pam pins
	// this; a mismatch against a running server is the signal to re-check.
	Version int `json:"version"`

	// Note carries the regeneration instruction into the artifact itself, so
	// someone reading a copy shipped with a release knows what produced it.
	Note string `json:"note"`

	// Endpoints is "METHOD /path", sorted.
	Endpoints []string `json:"endpoints"`

	// SSEEvents is every terminal event name the events endpoint can send.
	SSEEvents []string `json:"sse_events"`

	// Fixtures maps a repository-relative golden path to its SHA-256.
	Fixtures map[string]string `json:"fixtures"`
}

// note is the Note field's fixed text.
const note = "Generated by `make wire-contract`. version increments whenever any other " +
	"field changes; github.com/mnestor/ssoossh-pam pins it. Do not hand-edit."

// not covered: flag parsing and os.Exit around calls that are themselves
// tested (run and reportVersion, both exercised against a temp tree in
// main_test.go). Reaching this frame from a test means either exec'ing the
// binary or intercepting os.Exit, neither of which asserts anything the
// tests below do not already.
func main() {
	check := flag.Bool("check", false, "exit non-zero if the manifest would change")
	printVersion := flag.Bool("print-version", false, "print the committed contract version and exit")
	flag.Parse()

	if *printVersion {
		if err := reportVersion(); err != nil {
			fmt.Fprintf(os.Stderr, "genwirecontract: %v\n", err)
			os.Exit(1)
		}
		return
	}

	if err := run(*check); err != nil {
		fmt.Fprintf(os.Stderr, "genwirecontract: %v\n", err)
		os.Exit(1)
	}
}

// reportVersion prints the committed manifest's version. Deliberately the
// committed one rather than a freshly computed one: a caller asking for the
// version wants what is on disk, and a caller that needs to know whether that
// is current asks -check instead.
func reportVersion() error {
	m, err := load()
	if err != nil {
		return err
	}
	if m == nil {
		return fmt.Errorf("no %s yet; run 'make wire-contract' first", manifestPath)
	}
	fmt.Println(m.Version)
	return nil
}

// run builds the manifest, carries the version forward or bumps it, and
// writes or checks the result.
func run(check bool) error {
	built, err := build()
	if err != nil {
		return err
	}

	previous, err := load()
	if err != nil {
		return err
	}

	built.Version = nextVersion(previous, built)

	encoded, err := json.MarshalIndent(built, "", "  ")
	if err != nil {
		return fmt.Errorf("encode manifest: %w", err)
	}
	encoded = append(encoded, '\n')

	if check {
		current, readErr := os.ReadFile(manifestPath)
		if readErr != nil {
			return fmt.Errorf("read %s: %w", manifestPath, readErr)
		}
		if string(current) != string(encoded) {
			return fmt.Errorf("%s is stale; run 'make wire-contract'", manifestPath)
		}
		return nil
	}

	//nolint:gosec // a committed artifact, meant to be world-readable
	if err := os.WriteFile(manifestPath, encoded, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", manifestPath, err)
	}
	return nil
}

// nextVersion decides the version built should carry, given whatever is
// already committed.
//
// The whole mechanism turns on this: carrying the version forward when
// nothing moved is what keeps the generator idempotent, which is what lets
// wire-contract-check assert "regenerating changes nothing" the same way
// every other generated artifact does. Bumping when something moved is what
// puts the change in front of a reviewer.
//
// A first run starts at 1 rather than 0 so a pinned version is never
// mistaken for an unset one on the other side.
//
// The number only ever goes up, including when a change is reverted: reusing
// a version for a contract different from the one that version described is
// the one thing a pinned number must never do. Reverting a shape therefore
// produces a new version that happens to equal an older contract, which is
// correct — the other side still has to be told something moved.
func nextVersion(previous, built *manifest) int {
	switch {
	case previous == nil:
		return 1
	case sameContract(previous, built):
		return previous.Version
	default:
		return previous.Version + 1
	}
}

// build assembles everything except the version, which run decides.
func build() (*manifest, error) {
	endpoints, err := readEndpoints()
	if err != nil {
		return nil, err
	}

	fixtures, err := hashFixtures()
	if err != nil {
		return nil, err
	}

	// Sorted rather than in TerminalStatuses' declaration order: the manifest
	// is diffed, and reordering a constant block should not read as a
	// contract change.
	events := append([]string(nil), apitypes.TerminalStatuses()...)
	sort.Strings(events)

	return &manifest{
		Note:      note,
		Endpoints: endpoints,
		SSEEvents: events,
		Fixtures:  fixtures,
	}, nil
}

// load reads the committed manifest, returning nil when there isn't one yet.
func load() (*manifest, error) {
	data, err := os.ReadFile(manifestPath)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", manifestPath, err)
	}

	var m manifest
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parse %s: %w", manifestPath, err)
	}
	return &m, nil
}

// sameContract reports whether two manifests describe the same contract,
// ignoring the version. This is the comparison that decides a bump, so it
// deliberately covers every field except Version and Note.
func sameContract(a, b *manifest) bool {
	if !equalStrings(a.Endpoints, b.Endpoints) || !equalStrings(a.SSEEvents, b.SSEEvents) {
		return false
	}
	if len(a.Fixtures) != len(b.Fixtures) {
		return false
	}
	for path, sum := range b.Fixtures {
		if a.Fixtures[path] != sum {
			return false
		}
	}
	return true
}

// equalStrings compares two ordered slices element by element.
func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// specDocument is the sliver of OpenAPI this command reads: the path keys and,
// under each, the method keys. Everything else in the spec is deliberately
// ignored, so prose edits do not move the contract version.
type specDocument struct {
	Paths map[string]map[string]yaml.Node `yaml:"paths"`
}

// httpMethods are the path-item keys that name an operation. A path item also
// carries non-method keys ("parameters", "summary"), so this is an allowlist
// rather than "every key under the path".
var httpMethods = map[string]bool{
	"get": true, "put": true, "post": true, "delete": true,
	"options": true, "head": true, "patch": true, "trace": true,
}

// readEndpoints returns "METHOD /path" for every operation in the committed
// spec, sorted.
func readEndpoints() ([]string, error) {
	return readEndpointsFrom(specPath)
}

// readEndpointsFrom is readEndpoints against an arbitrary spec, so the parse
// can be tested without the repository's own 38-endpoint document.
func readEndpointsFrom(path string) ([]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}

	var doc specDocument
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if len(doc.Paths) == 0 {
		return nil, fmt.Errorf("%s declares no paths", path)
	}

	var endpoints []string
	for path, item := range doc.Paths {
		for method := range item {
			if httpMethods[strings.ToLower(method)] {
				endpoints = append(endpoints, strings.ToUpper(method)+" "+path)
			}
		}
	}
	sort.Strings(endpoints)
	return endpoints, nil
}

// hashFixtures returns a SHA-256 per golden file in the repository's own
// fixture trees.
func hashFixtures() (map[string]string, error) {
	return hashFixturesIn(fixtureGlobs)
}

// hashFixturesIn is hashFixtures over an arbitrary glob list, keyed by path
// with forward slashes so the manifest is identical whatever platform
// generated it.
func hashFixturesIn(globs []string) (map[string]string, error) {
	fixtures := map[string]string{}

	for _, glob := range globs {
		matches, err := filepath.Glob(glob)
		if err != nil {
			return nil, fmt.Errorf("glob %s: %w", glob, err)
		}
		if len(matches) == 0 {
			return nil, fmt.Errorf("%s matched no files; the goldens are missing, run the -update tests first", glob)
		}

		for _, match := range matches {
			data, err := os.ReadFile(match)
			if err != nil {
				return nil, fmt.Errorf("read %s: %w", match, err)
			}
			sum := sha256.Sum256(data)
			fixtures[filepath.ToSlash(match)] = hex.EncodeToString(sum[:])
		}
	}

	return fixtures, nil
}
