package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"

	clientcmd "github.com/mnestor/ssoossh/client/cmd"
)

// testTree builds a small command tree with the shapes the renderer has to
// handle: a persistent root flag, a nested group, a leaf with its own flags
// and an example, and a hidden command that must not appear.
func testTree() *cobra.Command {
	root := &cobra.Command{Use: "tool", Short: "A tool", Long: "Does <things> in `<code>`."}
	root.PersistentFlags().StringP("config", "c", "", "config file <path>")

	group := &cobra.Command{Use: "group", Short: "A group"}
	leaf := &cobra.Command{
		Use:     "leaf [flags]",
		Short:   "A leaf | with a pipe",
		Example: "tool group leaf --count 2",
		Run:     func(*cobra.Command, []string) {},
	}
	leaf.Flags().Int("count", 1, "how many")
	leaf.Flags().Bool("secret", false, "not shown")
	_ = leaf.Flags().MarkHidden("secret")
	group.AddCommand(leaf)

	hidden := &cobra.Command{Use: "hidden", Short: "Hidden", Hidden: true, Run: func(*cobra.Command, []string) {}}
	plain := &cobra.Command{Use: "plain", Short: "Plain", Run: func(*cobra.Command, []string) {}}

	root.AddCommand(group, hidden, plain)
	return root
}

// TestRender should produce one page per visible command and a sidebar in
// declaration order when given a nested tree.
func TestRender(t *testing.T) {
	root := testTree()
	pages, sidebar, err := render([]tree{{root: root, label: "tool", source: "x/cmd"}})
	if err != nil {
		t.Fatalf("render: %v", err)
	}

	want := []string{"tool/index.md", "tool/group.md", "tool/group-leaf.md", "tool/plain.md"}
	if len(pages) != len(want) {
		t.Fatalf("got %d pages, want %d: %v", len(pages), len(want), keys(pages))
	}
	for _, p := range want {
		if _, ok := pages[p]; !ok {
			t.Errorf("missing page %s", p)
		}
	}

	var items []sidebarItem
	if err := json.Unmarshal(sidebar, &items); err != nil {
		t.Fatalf("sidebar is not JSON: %v", err)
	}
	if len(items) != 1 || items[0].Label != "tool" {
		t.Fatalf("sidebar root = %+v", items)
	}
	labels := make([]string, 0, len(items[0].Items))
	for _, it := range items[0].Items {
		labels = append(labels, it.Label)
	}
	if got := strings.Join(labels, ","); got != "tool,group,plain" {
		t.Errorf("sidebar order = %s, want tool,group,plain", got)
	}
	if items[0].Items[1].Items[1].Slug != "reference/cli/tool/group-leaf" {
		t.Errorf("nested leaf slug = %q", items[0].Items[1].Items[1].Slug)
	}
}

// TestRenderPage should include every section a leaf command carries when
// the command has flags, inherited flags, and an example.
func TestRenderPage(t *testing.T) {
	root := testTree()
	leaf := root.Commands()[0].Commands()[0]
	page := string(renderPage(root, leaf, "x/cmd"))

	tests := []struct {
		name string
		want string
	}{
		{"frontmatter title", `title: "tool group leaf"`},
		{"eyebrow", `eyebrow: "CLI reference"`},
		{"generated marker", "Generated by genclidocs from the cobra command tree in x/cmd"},
		{"synopsis", "```\ntool group leaf [flags]\n```"},
		{"example", "```bash\ntool group leaf --count 2\n```"},
		{"own flag row", "| `--count` | int | `1` | how many |"},
		{"inherited flag row", "| `-c`, `--config` | string |  | config file &lt;path&gt; |"},
		{"parent link", "[`tool group`](/ssoossh/reference/cli/tool/group/)"},
		{"root link", "[`tool`](/ssoossh/reference/cli/tool/)"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if !strings.Contains(page, tc.want) {
				t.Errorf("page missing %q:\n%s", tc.want, page)
			}
		})
	}
	if strings.Contains(page, "secret") {
		t.Error("hidden flag rendered")
	}
}

// TestRenderPageRoot should list subcommands and omit See also when the
// command is the root.
func TestRenderPageRoot(t *testing.T) {
	root := testTree()
	page := string(renderPage(root, root, "x/cmd"))

	if !strings.Contains(page, "Does &lt;things&gt; in `<code>`.") {
		t.Errorf("prose not escaped outside code:\n%s", page)
	}
	if !strings.Contains(page, "| [`tool plain`](/ssoossh/reference/cli/tool/plain/) | Plain |") {
		t.Errorf("subcommand row missing:\n%s", page)
	}
	if strings.Contains(page, "hidden") {
		t.Error("hidden subcommand listed")
	}
	if strings.Contains(page, "## See also") {
		t.Error("root page has a See also section")
	}
}

// TestCell should escape pipes and collapse whitespace when a description
// contains both.
func TestCell(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want string
	}{
		{"pipe", "a | b", `a \| b`},
		{"newlines", "a\n  b\tc", "a b c"},
		{"angles outside code", "<x> `<y>`", "&lt;x&gt; `<y>`"},
		{"empty", "", ""},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := cell(tc.in); got != tc.want {
				t.Errorf("cell(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

// TestEscapeProse should leave fenced code untouched when a description
// mixes prose and a code block.
func TestEscapeProse(t *testing.T) {
	in := "use <a>\n```\n<b>\n```\nthen <c>"
	want := "use &lt;a&gt;\n```\n<b>\n```\nthen &lt;c&gt;"
	if got := escapeProse(in); got != want {
		t.Errorf("escapeProse = %q, want %q", got, want)
	}
}

// TestApply should write, report, and remove pages as the rendered set
// changes, and leave the disk alone in check mode.
func TestApply(t *testing.T) {
	dir := t.TempDir()
	site := filepath.Join(dir, "cli")
	sidebar := filepath.Join(dir, "cli-sidebar.json")

	pages := map[string][]byte{"tool/index.md": []byte("one"), "tool/plain.md": []byte("two")}
	sb := []byte("[]\n")

	// Check mode against an empty directory: everything is stale, nothing
	// is written.
	stale, err := apply(site, sidebar, pages, sb, true)
	if err != nil {
		t.Fatalf("apply check: %v", err)
	}
	if len(stale) != 3 {
		t.Errorf("check reported %d stale paths, want 3: %v", len(stale), stale)
	}
	if _, err := os.Stat(site); !os.IsNotExist(err) {
		t.Error("check mode created the site directory")
	}

	// Write mode creates everything; a second run is a no-op.
	if _, err := apply(site, sidebar, pages, sb, false); err != nil {
		t.Fatalf("apply write: %v", err)
	}
	stale, err = apply(site, sidebar, pages, sb, true)
	if err != nil {
		t.Fatalf("apply recheck: %v", err)
	}
	if len(stale) != 0 {
		t.Errorf("recheck reported stale paths after a write: %v", stale)
	}

	// Dropping a page removes it from disk and reports it.
	delete(pages, "tool/plain.md")
	stale, err = apply(site, sidebar, pages, sb, false)
	if err != nil {
		t.Fatalf("apply remove: %v", err)
	}
	if len(stale) != 1 || !strings.HasSuffix(stale[0], "plain.md") {
		t.Errorf("remove reported %v", stale)
	}
	if _, err := os.Stat(filepath.Join(site, "tool", "plain.md")); !os.IsNotExist(err) {
		t.Error("stale page still on disk")
	}
}

// TestListFilesMissingDir should return an empty set when the directory does
// not exist yet.
func TestListFilesMissingDir(t *testing.T) {
	files, err := listFiles(filepath.Join(t.TempDir(), "missing"))
	if err != nil {
		t.Fatalf("listFiles: %v", err)
	}
	if len(files) != 0 {
		t.Errorf("got %d files from a missing dir", len(files))
	}
}

// TestRunRealTrees should render the real client and server command trees
// without error when both are built, and produce the pages the man pages
// also have.
func TestRunRealTrees(t *testing.T) {
	clientRoot, err := clientcmd.CobraCommandForManpage()
	if err != nil {
		t.Fatalf("client tree: %v", err)
	}
	pages, sidebar, err := render([]tree{{root: clientRoot, label: "ssoossh (client)", source: "client/cmd"}})
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	if _, ok := pages["ssoossh/ssh-login.md"]; !ok {
		t.Errorf("client tree produced no ssh login page: %v", keys(pages))
	}
	if !strings.Contains(string(sidebar), `"slug": "reference/cli/ssoossh/host-mapping-add"`) {
		t.Errorf("sidebar lacks the nested host mapping add entry:\n%s", sidebar)
	}
}

// keys lists a page map's paths for a failure message.
func keys(m map[string][]byte) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}
