---
# https url of the ssoossh server
# This is the server that will be used to retrieve the ssh certificates
#server: https://ssoossh.example.com

# Verify the SSL certificate of the server
verify-ssl: true

# Verify server name is in certificate
verify-server-name: true

# SHA256 Fingerprint of the ssl certificate of the server
# This is used to verify the server's identity to make sure the server
# we expect is the one we are connecting to.
#echo | openssl s_client -connect ssh.nanestor.us:443 -servername ssh.example.com 2>&1| openssl x509 -noout -fingerprint -md5
#ssl-fingerprint: 3B:6E:1A:...:I7:J8

# CA of the server signing key so you don't need to retrieve it
# with every run of ssoossh
#ca: ssh-rsa AAAA....

# Skip retrieving the CA certificate from the server
# Useful if you set the CA in the config file
skip-ca: false

# Use an ssh-agent to store your ssh keys and certificate
use-agent: true

# Fall back to ssh key files if the agent is not available
fallback-to-file: true

# What key type should we create ssh keys with
key-type: ed25519

# If RSA then how large should the key be
key-size: 4096

ssh-key-identity-file: ~/.ssh/id_ssoossh
