package cmd

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/bep/simplecobra"

	"github.com/mnestor/ssoossh/client/config"
	"github.com/mnestor/ssoossh/internal/api"
	"github.com/mnestor/ssoossh/internal/crypto/ssh/keypair"
)

func newServiceEnrollCommand() simplecobra.Commander {
	var publicKeyPath string
	var generatePath string

	cmd := &simpleCommand{
		name:  "enroll",
		short: "Enroll a service keypair for unattended certificate issuance.",
		long: "The keypair is either operator-supplied via --public-key (the server never sees the " +
			"private half) or generated by --generate. After OIDC approval, the server " +
			"returns an enrollment code bound to both the public key and the authorized " +
			"option set; `service retrieve` posts only that code on later invocations.\n\n" +
			"The code is printed once and stored nowhere. Save it where the unattended job " +
			"that runs `service retrieve` can read it.",
		init: func(cd *simplecobra.Commandeer) error {
			cd.CobraCommand.Flags().StringVar(&publicKeyPath, "public-key", "",
				"path to an existing public key file (authorized_keys format) to enroll")
			cd.CobraCommand.Flags().StringVar(&generatePath, "generate", "",
				"generate a keypair, writing the private key to this path and the "+
					"public key to <path>.pub")
			return nil
		},
		run: func(ctx context.Context, cd *simplecobra.Commandeer, root *RootCommand, args []string) error {
			return runServiceEnroll(ctx, root, os.Stdout, publicKeyPath, generatePath)
		},
	}
	return cmd
}

// runServiceEnroll enrolls a public key and prints the resulting enrollment
// code. Exactly one of publicKeyPath (enroll a key the operator already
// has) or generatePath (generate one here) is required: there is no
// implicit mode, because each writes a different set of files and the
// printed instructions have to name the right ones.
func runServiceEnroll(ctx context.Context, root *RootCommand, out io.Writer, publicKeyPath, generatePath string) error {
	cfg := root.Config()

	if err := checkEnrollKeySelection(publicKeyPath, generatePath); err != nil {
		return err
	}

	var publicKey string
	var err error
	if publicKeyPath != "" {
		pubData, readErr := os.ReadFile(publicKeyPath)
		if readErr != nil {
			return fmt.Errorf("read public key file: %w", readErr)
		}
		publicKey = string(pubData)
	} else {
		publicKey, err = generateServiceKeypair(cfg, generatePath)
		if err != nil {
			return err
		}
	}

	pending, err := root.API().CreateServiceEnrollment(ctx, publicKey, api.RequestedOptions{})
	if err != nil {
		return fmt.Errorf("request enrollment: %w", err)
	}

	fmt.Fprintf(out, "Approve this request in your browser:\n\n    %s\n\n", pending.ApprovalURL)
	if cfg.TryOpenBrowser {
		openBrowser(ctx, out, pending.ApprovalURL)
	}
	fmt.Fprintln(out, "Waiting for approval…")

	result, err := root.API().AwaitCertificate(ctx, pending)
	if err != nil {
		return describeWaitError(err)
	}

	code, err := enrollmentCode(result)
	if err != nil {
		return err
	}

	printEnrollmentCode(out, code, publicKeyPath, generatePath)
	return nil
}

// checkEnrollKeySelection requires exactly one key source. Neither is an
// error rather than a default because the previous implicit-generate
// behavior wrote the private key into a file the operator never named.
func checkEnrollKeySelection(publicKeyPath, generatePath string) error {
	switch {
	case publicKeyPath == "" && generatePath == "":
		return errors.New("choose a key source: --public-key <public-key-file> to enroll a key you already have, " +
			"or --generate <private-key-file> to generate one")
	case publicKeyPath != "" && generatePath != "":
		return errors.New("--public-key and --generate are mutually exclusive: --public-key enrolls a key you " +
			"already have, --generate creates a new one")
	}
	return nil
}

// generateServiceKeypair generates a keypair for the enrollment, writing
// the private key to privateKeyPath (0600) and the public key alongside it
// as <path>.pub (0644), and returns the public key in authorized_keys
// form. Neither file is overwritten if it already exists: clobbering a
// private key destroys every certificate that depends on it.
func generateServiceKeypair(cfg *config.Config, privateKeyPath string) (string, error) {
	publicKeyPath := publicKeyPathFor(privateKeyPath)
	for _, path := range []string{privateKeyPath, publicKeyPath} {
		if _, err := os.Stat(path); err == nil {
			return "", fmt.Errorf("%s already exists; remove it or choose another path for --generate", path)
		} else if !errors.Is(err, os.ErrNotExist) {
			return "", fmt.Errorf("check %s: %w", path, err)
		}
	}

	algorithm, size, _, err := cfg.ResolveSSHKey()
	if err != nil {
		return "", fmt.Errorf("invalid ssh key configuration: %w", err)
	}

	kp, err := keypair.NewSSHKeypair(algorithm, size)
	if err != nil {
		return "", fmt.Errorf("generate keypair: %w", err)
	}

	publicKey, err := kp.MarshalAuthorizedKey()
	if err != nil {
		return "", fmt.Errorf("encode public key: %w", err)
	}
	privatePEM, err := kp.MarshalPrivateKey()
	if err != nil {
		return "", fmt.Errorf("encode private key: %w", err)
	}

	// Private key first: a public key with no private half beside it is a
	// clearer failure than the reverse.
	if err := writeFileAtomic(privateKeyPath, privatePEM, 0600); err != nil {
		return "", err
	}
	if err := writeFileAtomic(publicKeyPath, []byte(publicKey), 0644); err != nil {
		return "", err
	}

	return publicKey, nil
}

// publicKeyPathFor is the OpenSSH convention: the public key sits beside
// the private key with a .pub suffix.
func publicKeyPathFor(privateKeyPath string) string { return privateKeyPath + ".pub" }

// certificatePathFor is the OpenSSH convention for where a certificate
// belongs relative to its key: id_ed25519 and id_ed25519.pub both give
// id_ed25519-cert.pub.
func certificatePathFor(keyPath string) string {
	return strings.TrimSuffix(keyPath, ".pub") + "-cert.pub"
}

// printEnrollmentCode prints the code and the exact commands to use it.
// The code is shown rather than stored: it is a bearer credential for
// certificates on the service account, and the operator has to place it
// wherever the unattended job will read it. Printing it without saying how
// to use it just moves the problem, so the retrieve command is spelled out
// with the certificate path derived from the key that was enrolled.
func printEnrollmentCode(out io.Writer, code, publicKeyPath, generatePath string) {
	keySource := publicKeyPath
	if generatePath != "" {
		keySource = generatePath
		fmt.Fprintf(out, "\nPrivate key written to %s\n", generatePath)
		fmt.Fprintf(out, "Public key written to  %s\n", publicKeyPathFor(generatePath))
	}

	fmt.Fprintf(out, "\nEnrollment code (shown once, and stored nowhere):\n\n    %s\n\n", code)
	fmt.Fprintln(out, "Save it now. To retrieve a certificate:")
	fmt.Fprintf(out, "\n    export SSOOSSH_ENROLLMENT_CODE=%s\n", code)
	fmt.Fprintf(out, "    ssoossh service retrieve --output %s\n\n", certificatePathFor(keySource))
	fmt.Fprintln(out, "The code is reusable, so that is safe to run from cron or a systemd timer.")
	fmt.Fprintln(out, "Anyone holding it can obtain certificates for this service account until the")
	fmt.Fprintln(out, "enrollment expires, so keep it as secret as the private key.")
}

// enrollmentCode extracts the enrollment code from a resolved service
// request. Unlike ssh login's checkOutcome, the outcome this path wants is
// "enrolled" — the server mints a code at approval, and the certificate
// itself is only issued later when `service retrieve` redeems it.
func enrollmentCode(result *api.CertificateResult) (string, error) {
	if result == nil {
		return "", errors.New("the enrollment request resolved with no outcome")
	}

	switch result.Status {
	case api.StatusEnrolled:
		if result.Code == "" {
			return "", errors.New("the request was enrolled but no code was delivered; run service enroll again")
		}
		return result.Code, nil
	case api.StatusDenied:
		return "", errors.New("the request was denied, so no enrollment was created")
	case api.StatusExpired:
		return "", errors.New("the request expired before anyone approved it; run service enroll again")
	case api.StatusFailed:
		return "", errors.New("ssoosshd could not create the enrollment; check the server logs, then run service enroll again")
	default:
		return "", fmt.Errorf("the server reported an unrecognized outcome %q", result.Status)
	}
}
