-- The process's group id, alongside the uid the host context already
-- carried. See https://mnestor.github.io/ssoossh/internals/host-context/.
--
-- Added with the Go client, which reports the whole host context a user
-- certificate previously had no way to send. One column whichever
-- implementation filled it: pam_ssoossh does not report a gid yet, and the
-- wire type accepts one from every request type so it will not need a
-- second migration when it does.
--
-- NULL means not reported, which is why it takes no default: gid 0 is a
-- value, and on Windows there is no gid at all.
ALTER TABLE certificate_requests ADD COLUMN caller_gid INTEGER;
