#!/usr/bin/env bash
# Regenerates THIRD-PARTY-LICENSES.md from the license file bundled with each
# Go module dependency in the local module cache. Run before packaging a
# release (see .goreleaser*.yml before.hooks) so every distributed archive
# carries attribution for its statically-linked dependencies.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="THIRD-PARTY-LICENSES.md"

{
	echo "# Third-Party Licenses"
	echo
	echo "Generated by scripts/gen-third-party-licenses.sh — do not edit by hand."
	echo "Lists the license of every Go module dependency present in the build."
	echo
} >"$OUT"

MODULE=$(go list -m)

go list -m -f '{{.Path}} {{.Dir}}' all | while read -r path dir; do
	[ "$path" = "$MODULE" ] && continue
	[ -z "$dir" ] && continue
	lic=$(find "$dir" -maxdepth 1 -type f \( -iname 'LICENSE*' -o -iname 'LICENCE*' -o -iname 'COPYING*' \) | sort | head -1)
	[ -z "$lic" ] && continue
	{
		echo "---"
		echo
		echo "## $path"
		echo
		echo '```'
		cat "$lic"
		echo '```'
		echo
	} >>"$OUT"
done
