#!/usr/bin/env bash
#
# Build the wire-contract bundle shipped with each release.
#
# Why a release asset: pam_ssoossh (github.com/mnestor/ssoossh-pam) is a
# separate project written in C. It shares no code with this repository, so
# nothing at compile time tells it that a JSON field was renamed or that an
# SSE event changed shape. What it can do instead is pin a contract version
# and test its own decoder against the same golden files this repository
# tests its Go one against -- but only if those files are published somewhere
# a build without a Go toolchain can fetch them.
#
# The bundle is that: the spec, the versioned manifest, and every golden
# fixture, in one tarball attached to the release. A consumer fetches the
# tarball for the version it pins, runs its parser over each fixture, and
# fails its own build when its decoder and this server disagree.
#
# docs/wire-contract.json is also uploaded loose (see .goreleaser.yml's
# release.extra_files) so a consumer can read the version with one curl,
# without downloading the fixtures.
#
# Usage: scripts/gen-wire-contract-bundle.sh [output-directory]
#
# Defaults to .wire-contract/, deliberately NOT dist/: goreleaser runs with
# --clean, which removes dist/ before it does anything else, so a bundle
# staged there would be deleted before release.extra_files ever globs for it.

set -euo pipefail

OUT_DIR="${1:-.wire-contract}"
BUNDLE_NAME="ssoossh-wire-contract"

# Everything the contract consists of. openapi.yaml and wire-contract.json
# describe it; the two testdata trees are the shapes themselves -- the JSON
# payloads and the raw SSE framing respectively.
readonly SOURCES=(
	docs/openapi.yaml
	docs/wire-contract.json
	internal/apitypes/testdata
	server/controller/testdata
)

for src in "${SOURCES[@]}"; do
	if [ ! -e "$src" ]; then
		echo "missing $src -- run 'make wire-contract' from the repository root first" >&2
		exit 1
	fi
done

# Refuse to ship a stale manifest. The tarball is immutable once released and
# a consumer pins its version, so a bundle whose version does not match its
# fixtures is worse than no bundle: it tells the other side nothing changed
# while shipping shapes that did.
if ! go run ./internal/tools/genwirecontract -check >/dev/null 2>&1; then
	echo "docs/wire-contract.json is stale -- run 'make wire-contract' and commit before releasing" >&2
	exit 1
fi

VERSION=$(go run ./internal/tools/genwirecontract -print-version)

STAGE=$(mktemp -d)
trap 'rm -rf "$STAGE"' EXIT

ROOT="$STAGE/$BUNDLE_NAME"
mkdir -p "$ROOT/fixtures"

cp docs/openapi.yaml docs/wire-contract.json "$ROOT/"
cp internal/apitypes/testdata/*.json "$ROOT/fixtures/"
cp server/controller/testdata/sse_stream_*.sse "$ROOT/fixtures/"

# A README inside the tarball, because the person who opens it is on the
# other side of a repository boundary and has no access to the comments that
# explain any of this.
cat >"$ROOT/README.md" <<EOF
# ssoossh wire contract, version $VERSION

What ssoosshd puts on the wire, as data rather than prose. Published so an
implementation that shares no code with ssoossh can test itself against the
same shapes ssoossh tests itself against.

| File | What it is |
| --- | --- |
| \`openapi.yaml\` | The HTTP API: endpoints, request and response schemas |
| \`wire-contract.json\` | The version, the endpoint set, the terminal SSE event names, and a SHA-256 per fixture |
| \`fixtures/*.json\` | One encoded instance of each wire type. \`.full\` has every field set; \`.zero\` shows which fields disappear under \`omitempty\` |
| \`fixtures/sse_payload_*.json\` | The envelope carried by each terminal SSE event |
| \`fixtures/sse_stream_*.sse\` | The raw bytes of each terminal event, framing included |

## How to use it

Point your test suite at \`fixtures/\`. For each file, decode it with your own
decoder and assert the values are what you expect. A field rename on the
server side changes a fixture, which changes its hash, which bumps
\`version\` in \`wire-contract.json\`.

Pin \`version\` in your build. When it moves, read the diff before upgrading.

## Two things that are easy to get wrong

**The SSE event name carries the status, and the payload does not.** Look at
\`fixtures/sse_stream_denied.sse\`: the body is \`{"data":{}}\`. A reader that
only decodes the data line cannot tell an approval from a denial. The status
is in the \`event:\` line and nowhere else.

**There is no space after the colon.** The framing is \`event:approved\`, not
\`event: approved\`. The space is optional in the SSE grammar and most
examples include it; this server does not emit it. Split on the first colon,
then strip an optional leading space, per the WHATWG rules.

Generated by \`make wire-contract-bundle\` in github.com/mnestor/ssoossh.
EOF

mkdir -p "$OUT_DIR"
TARBALL="$OUT_DIR/${BUNDLE_NAME}.tar.gz"

# --sort=name and a fixed mtime so the same contract produces the same bytes:
# a tarball that differs run to run makes the checksum file noise rather than
# evidence.
tar --sort=name \
	--mtime='UTC 2020-01-01' \
	--owner=0 --group=0 --numeric-owner \
	-czf "$TARBALL" \
	-C "$STAGE" "$BUNDLE_NAME"

echo "wrote $TARBALL (wire contract version $VERSION)"
