#!/usr/bin/env bash
# Regenerates the target inventory in Makefile.md from the Makefile's own
# `##@` section headers and `## description` annotations -- the same data
# `make help` prints.
#
# Only the region between the BEGIN/END markers is rewritten. Everything
# outside them is hand-written rationale (why lint-fix runs before lint, what
# hides code from the obvious command) that no generator can produce and that
# adding a target does not invalidate.
#
# Run via `make makefile-docs`; gated by `make makefile-docs-check`.
set -euo pipefail

MAKEFILE=${1:-Makefile}
DOC=${2:-Makefile.md}

BEGIN_MARKER='<!-- BEGIN GENERATED TARGETS -->'
END_MARKER='<!-- END GENERATED TARGETS -->'

if ! grep -qF "$BEGIN_MARKER" "$DOC" || ! grep -qF "$END_MARKER" "$DOC"; then
	echo "$DOC is missing the generated-region markers:" >&2
	echo "  $BEGIN_MARKER" >&2
	echo "  $END_MARKER" >&2
	exit 1
fi

table=$(awk '
	BEGIN { FS = ":.*##" }
	/^##@/ {
		seen_section = 1
		printf "\n### %s\n\n", substr($0, 5)
		printf "| Target | What it does |\n| --- | --- |\n"
		next
	}
	# Targets defined before the first ##@ header (help) belong to no
	# section; the table they would start has no heading, so skip them.
	/^[a-zA-Z0-9_-]+:.*?##/ {
		if (!seen_section) next
		desc = $2
		sub(/^[ \t]+/, "", desc)
		gsub(/\|/, "\\|", desc)
		# < and > would be parsed as HTML in a markdown table cell.
		gsub(/</, "\\&lt;", desc)
		gsub(/>/, "\\&gt;", desc)
		printf "| `make %s` | %s |\n", $1, desc
	}
' "$MAKEFILE")

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v table="$table" '
	index($0, begin) { print; print ""; print "<!-- Generated by scripts/gen-makefile-docs.sh. Do not edit by hand;"; print "     edit the ## annotations in the Makefile and run `make makefile-docs`. -->"; print table; skip = 1; next }
	index($0, end)   { skip = 0 }
	!skip { print }
' "$DOC" >"$tmp"

mv "$tmp" "$DOC"
trap - EXIT
