---

traces: false
metrics: false
server:
  address: 127.0.0.1
  port: 80
  trusted_proxies: 
    - 127.0.0.1
  unix_socket: ""
  unix_socket_mode: 0600
  domain: ""
  cookiekey: ""
  ratelimit: 50
  rateduration: 60
  hsts: ""

app_url: ""
sshcakey: ""
sshcakeyfile: ""

db:
  provider: "sqlite"
  connection_string: "ssoossh.db"
  log_level: ""
  
oauth:
  providerurl: ""
  clientid: ""
  clientsecret: ""
  scopes:
    - profile
    - email
  admin_group: ""
