package confdocs

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// mdGenerated marks every generated page so a reader landing in the file
// knows where the content is decided. An HTML comment renders to nothing.
const mdGenerated = "<!-- Generated by genconfdocs from the config structs in server/config. Do not edit. -->"

// MarkdownPages renders the configuration surface as one Starlight page per
// section, plus an index page linking them. The map is keyed by filename.
//
// Same division of labour as the man page: the walk supplies the prose and
// the types, defaults.yaml supplies the values, and a key defaults.yaml
// leaves unset is described by its Go zero value, since that is what viper
// hands the server either way.
func MarkdownPages(sections []*Section, defaults *Defaults) map[string]string {
	pages := map[string]string{"index.md": markdownIndex(sections)}
	for i, s := range sections {
		pages[markdownFilename(s)] = markdownSection(sections, s, defaults, i+1)
	}
	return pages
}

// markdownFilename is the page filename for a section. The synthetic section
// holding Config's own scalars has no key, so it gets a name of its own.
func markdownFilename(s *Section) string {
	if s.Key == "" {
		return "top-level.md"
	}
	return s.Key + ".md"
}

// markdownTitle is the page title for a section.
func markdownTitle(s *Section) string {
	if s.Key == "" {
		return "Top-level keys"
	}
	return s.Key
}

// markdownIndex renders the reference overview: one link per section with the
// same gloss its own page carries, so the list reads as a table of contents.
func markdownIndex(sections []*Section) string {
	var b strings.Builder
	writeMDFrontmatter(&b, "Configuration reference",
		"Every ssoosshd configuration key, generated from the server's config structs.", 0)

	b.WriteString("Every `ssoosshd.yaml` key, one page per top-level section. " +
		"The pages are generated from the Go structs in `server/config` -- the same " +
		"source that produces the `ssoosshd.yaml(5)` man page and the annotated " +
		"defaults file shipped to `/etc/ssoossh/ssoosshd.yaml`.\n\n")

	for _, s := range sections {
		slug := strings.TrimSuffix(markdownFilename(s), ".md")
		entry := fmt.Sprintf("- [%s](./%s/)", markdownTitle(s), slug)
		if gloss := firstSentence(s.Doc); gloss != "" {
			entry += " -- " + gloss
		}
		b.WriteString(entry + "\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// markdownSection renders one section page: frontmatter, the section's own
// prose, then every key beneath it as a flat run of headings, the same shape
// the man page uses so the two stay recognisably the same document.
func markdownSection(sections []*Section, s *Section, defaults *Defaults, order int) string {
	refs := CrossRefsIn(sections, s.Key)

	var b strings.Builder
	writeMDFrontmatter(&b, markdownTitle(s), firstSentence(s.Doc), order)
	writeMDProse(&b, sectionBody(s), refs, s.Key)
	for _, f := range s.Fields {
		writeMDField(&b, f, defaults, refs, s.Key, s.Key)
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// writeMDFrontmatter emits the Starlight frontmatter plus the generated
// marker. The description doubles as the gloss under the title and the text
// search results show; order pins the autogenerated sidebar to declaration
// order rather than the alphabetical fallback.
func writeMDFrontmatter(b *strings.Builder, title, description string, order int) {
	b.WriteString("---\n")
	fmt.Fprintf(b, "title: %s\n", strconv.Quote(title))
	if description != "" {
		fmt.Fprintf(b, "description: %s\n", strconv.Quote(description))
	}
	fmt.Fprintf(b, "sidebar:\n  order: %d\n", order)
	b.WriteString("---\n\n")
	b.WriteString(mdGenerated + "\n\n")
}

// writeMDField emits one key, recursing into nested structs so that
// http.tls.min_version appears on the http page. A struct's own prose is
// kept under its dotted path -- the man page drops it, but a web page has
// the room, and the group comment is where shape-of-the-block prose lives.
func writeMDField(b *strings.Builder, f *Field, defaults *Defaults, refs map[string]string, scope, parent string) {
	if f.IsStruct() {
		if len(f.Doc) > 0 && f.Path != "" {
			fmt.Fprintf(b, "## `%s`\n\n", f.Path)
			writeMDProse(b, f.Doc, refs, scope)
		}
		for _, c := range f.Children {
			writeMDField(b, c, defaults, refs, scope, f.Path)
		}
		return
	}

	// The embedded rotation options have no path of their own; they land in
	// the namespace of the struct that embeds them.
	if f.Embedded {
		fmt.Fprintf(b, "## `%s.*`\n\n", parent)
		writeMDProse(b, f.Doc, refs, scope)
		return
	}

	fmt.Fprintf(b, "## `%s`\n\n", f.Path)
	line := fmt.Sprintf("`%s`", f.Type)
	if d := defaults.Describe(f); d != "" {
		line += fmt.Sprintf(", default `%s`", d)
	}
	b.WriteString(line + "\n\n")
	writeMDProse(b, f.Doc, refs, scope)
}

// writeMDProse converts doc-comment lines into Markdown body text: Go field
// names rewritten to backticked config keys, blank lines kept as paragraph
// breaks, and indented example blocks fenced as YAML with their common
// indentation stripped.
func writeMDProse(b *strings.Builder, doc []string, refs map[string]string, scope string) {
	backtick := func(path string) string { return "`" + path + "`" }

	var example []string
	flushExample := func() {
		if len(example) == 0 {
			return
		}
		b.WriteString("```yaml\n")
		for _, l := range trimCommonIndent(example) {
			b.WriteString(l + "\n")
		}
		b.WriteString("```\n\n")
		example = nil
	}

	for _, line := range StripGoOnlyRefs(doc, refs) {
		switch {
		case strings.TrimSpace(line) == "":
			flushExample()
		case strings.HasPrefix(line, " ") || strings.HasPrefix(line, "\t"):
			example = append(example, line)
		default:
			flushExample()
			b.WriteString(rewriteRefsWith(line, refs, scope, backtick) + "\n\n")
		}
	}
	flushExample()
}

// trimCommonIndent strips the longest whitespace prefix shared by every line,
// so a doc-comment example keeps its internal nesting but starts at column
// zero inside the fence.
func trimCommonIndent(lines []string) []string {
	prefix := ""
	for i, l := range lines {
		indent := l[:len(l)-len(strings.TrimLeft(l, " \t"))]
		if i == 0 || strings.HasPrefix(prefix, indent) {
			prefix = indent
			continue
		}
		for !strings.HasPrefix(indent, prefix) {
			prefix = prefix[:len(prefix)-1]
		}
	}

	out := make([]string, 0, len(lines))
	for _, l := range lines {
		out = append(out, strings.TrimPrefix(l, prefix))
	}
	return out
}

// WriteMarkdown renders the section pages into dir, creating it if needed,
// and removes any .md file there that the walk no longer produces -- the
// directory is wholly generated, so a leftover page is a section that no
// longer exists. Reports whether anything changed.
func WriteMarkdown(dir string, sections []*Section, defaults *Defaults) (bool, error) {
	pages := MarkdownPages(sections, defaults)

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return false, fmt.Errorf("create %s: %w", dir, err)
	}

	names := make([]string, 0, len(pages))
	for name := range pages {
		names = append(names, name)
	}
	sort.Strings(names)

	changed := false
	for _, name := range names {
		path := filepath.Join(dir, name)
		before, err := os.ReadFile(path)
		if err == nil && string(before) == pages[name] {
			continue
		}
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return false, fmt.Errorf("read %s: %w", path, err)
		}
		if err := os.WriteFile(path, []byte(pages[name]), 0o600); err != nil {
			return false, fmt.Errorf("write %s: %w", path, err)
		}
		changed = true
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return false, fmt.Errorf("read %s: %w", dir, err)
	}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".md") {
			continue
		}
		if _, ok := pages[name]; ok {
			continue
		}
		if err := os.Remove(filepath.Join(dir, name)); err != nil {
			return false, fmt.Errorf("remove stale page %s: %w", name, err)
		}
		changed = true
	}
	return changed, nil
}
