package confdocs

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// mdGenerated marks every generated page so a reader landing in the file
// knows where the content is decided. An HTML comment renders to nothing.
const mdGenerated = "<!-- Generated by genconfdocs from the config structs in server/config. Do not edit. -->"

// mdBase is the site-absolute path of the config reference. Relative links
// would break on any URL served without a trailing slash, so every link is
// written absolute -- which couples this to the `base` in
// user-docs/astro.config.mjs.
const mdBase = "/ssoossh/reference/config/"

// mdSplitSectionMinLeaves is how many keys a section needs before its big
// groups move to pages of their own. A ten-key section reads fine as one
// page even when most of its keys sit in one group (db and its logging);
// past this line (http, cert_options) a single page is overwhelming.
const mdSplitSectionMinLeaves = 15

// mdSplitChildMinLeaves is how many keys a struct-valued child needs to get
// its own page once its section splits at all. Small groups (a two-key rate
// limit) read better inline.
const mdSplitChildMinLeaves = 4

// mdDefaultMax is the longest default shown in an at-a-glance table cell
// before it is truncated; the full value is always on the key's own entry.
const mdDefaultMax = 40

// MarkdownPages renders the configuration surface as Starlight pages, keyed
// by filename relative to the reference directory.
//
// Each section is one page -- an intro, an at-a-glance table of every key,
// then one heading per key -- except that a struct-valued child with
// mdSplitMinLeaves or more keys is split out to its own page under a
// directory named for the section (http/tls.md), with the section's index
// page keeping the full key table so the whole surface stays scannable in
// one place. Either way a section's URL is <base><key>/.
//
// Same division of labour as the man page: the walk supplies the prose and
// the types, defaults.yaml supplies the values, and a key defaults.yaml
// leaves unset is described by its Go zero value, since that is what viper
// hands the server either way.
func MarkdownPages(sections []*Section, defaults *Defaults) map[string]string {
	pages := map[string]string{"index.md": markdownIndex(sections)}
	for _, s := range sections {
		split := splitChildren(s)
		if len(split) == 0 {
			pages[markdownFilename(s)] = markdownSection(sections, s, defaults)
			continue
		}
		pages[s.Key+"/index.md"] = markdownSection(sections, s, defaults)
		for _, c := range split {
			pages[s.Key+"/"+c.Key+".md"] = markdownSubpage(sections, s, c, defaults)
		}
	}
	return pages
}

// splitChildren returns the section's direct struct children big enough for
// a page of their own, in declaration order. A section below the size line
// never splits, however its keys are grouped.
func splitChildren(s *Section) []*Field {
	total := 0
	for _, f := range s.Fields {
		total += leafCount(f)
		if !f.IsStruct() && !f.Embedded {
			total++
		}
	}
	if total < mdSplitSectionMinLeaves {
		return nil
	}

	var out []*Field
	for _, f := range s.Fields {
		if f.IsStruct() && leafCount(f) >= mdSplitChildMinLeaves {
			out = append(out, f)
		}
	}
	return out
}

// leafCount counts the value-carrying keys under f. An embedded group is one
// documented surface, so it counts once.
func leafCount(f *Field) int {
	n := 0
	for _, c := range f.Children {
		switch {
		case c.IsStruct():
			n += leafCount(c)
		default:
			n++
		}
	}
	return n
}

// markdownFilename is the page filename for an unsplit section. The
// synthetic section holding Config's own scalars has no key, so it gets a
// name of its own.
func markdownFilename(s *Section) string {
	if s.Key == "" {
		return "top-level.md"
	}
	return s.Key + ".md"
}

// markdownTitle is the page title for a section.
func markdownTitle(s *Section) string {
	if s.Key == "" {
		return "Top-level keys"
	}
	return s.Key
}

// sectionURL is the site-absolute URL of a section's page, split or not.
func sectionURL(s *Section) string {
	return mdBase + strings.TrimSuffix(markdownFilename(s), ".md") + "/"
}

// markdownIndex renders the reference overview: one table row per section
// with the same gloss its own page carries.
func markdownIndex(sections []*Section) string {
	var b strings.Builder
	writeMDFrontmatter(&b, "Configuration reference",
		"Every ssoosshd configuration key, generated from the server's config structs.")

	b.WriteString("Every `ssoosshd.yaml` key, one page per top-level section. " +
		"The pages are generated from the Go structs in `server/config` -- the same " +
		"source that produces the `ssoosshd.yaml(5)` man page and the annotated " +
		"defaults file shipped to `/etc/ssoossh/ssoosshd.yaml`.\n\n")

	b.WriteString("| Section | Configures |\n| --- | --- |\n")
	for _, s := range sections {
		gloss := firstSentence(s.Doc)
		fmt.Fprintf(&b, "| [%s](%s) | %s |\n", markdownTitle(s), sectionURL(s), mdCell(gloss))
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// markdownSection renders a section's page. For a split section this is the
// directory's index: its table still lists every key in the section, with
// the split-out ones linking into their own pages, so the section stays
// scannable from one screen; only the split keys' details move.
func markdownSection(sections []*Section, s *Section, defaults *Defaults) string {
	refs := CrossRefsIn(sections, s.Key)
	split := splitChildren(s)
	isSplit := map[*Field]bool{}
	for _, c := range split {
		isSplit[c] = true
	}

	var b strings.Builder
	writeMDFrontmatter(&b, markdownTitle(s), firstSentence(s.Doc))
	writeMDProse(&b, sectionBody(s), refs, s.Key)

	// The at-a-glance table: local keys anchor down the page, split keys
	// link into their subpage. Each subpage gets its own slug sequence,
	// mirroring how that page will render.
	slugs := newSlugger()
	rows := &strings.Builder{}
	for _, f := range s.Fields {
		if isSplit[f] {
			sub := sectionURL(s) + f.Key + "/"
			subSlugs := newSlugger()
			for _, c := range f.Children {
				mdTableRows(rows, c, defaults, sub, f.Path, f.Path, subSlugs)
			}
			continue
		}
		mdTableRows(rows, f, defaults, "", s.Key, s.Key, slugs)
	}
	writeMDTable(&b, rows.String())

	slugs = newSlugger()
	for _, f := range s.Fields {
		if isSplit[f] {
			continue
		}
		writeMDField(&b, f, defaults, refs, s.Key, s.Key, s.Key, slugs)
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// markdownSubpage renders one split-out struct child as its own page.
func markdownSubpage(sections []*Section, s *Section, c *Field, defaults *Defaults) string {
	refs := CrossRefsIn(sections, s.Key)

	var b strings.Builder
	writeMDFrontmatter(&b, c.Path, firstSentence(c.Doc))
	writeMDProse(&b, c.Doc, refs, s.Key)

	slugs := newSlugger()
	rows := &strings.Builder{}
	for _, f := range c.Children {
		mdTableRows(rows, f, defaults, "", c.Path, c.Path, slugs)
	}
	writeMDTable(&b, rows.String())

	slugs = newSlugger()
	for _, f := range c.Children {
		writeMDField(&b, f, defaults, refs, s.Key, c.Path, c.Path, slugs)
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// writeMDTable emits the at-a-glance table around the prepared rows.
func writeMDTable(b *strings.Builder, rows string) {
	if rows == "" {
		return
	}
	b.WriteString("| Key | Type | Default |\n| --- | --- | --- |\n")
	b.WriteString(rows)
	b.WriteString("\n")
}

// mdTableRows emits one table row per value-carrying key under f: the full
// dotted path (so the table is what an operator greps and copies from),
// linked to the key's entry -- an anchor on this page, or page+anchor when
// the details live on a subpage. parent is the enclosing struct's path,
// which is what an embedded group's keys land under.
func mdTableRows(b *strings.Builder, f *Field, defaults *Defaults, page, scope, parent string, slugs *slugger) {
	if f.IsStruct() {
		if len(f.Doc) > 0 && f.Path != "" {
			// The group's own heading takes a slug; count it so the leaf
			// anchors that follow stay aligned with the rendered page.
			slugs.slug(relName(f.Path, scope))
		}
		for _, c := range f.Children {
			mdTableRows(b, c, defaults, page, scope, f.Path, slugs)
		}
		return
	}

	if f.Embedded {
		name := embeddedName(parent, scope)
		fmt.Fprintf(b, "| [`%s.*`](%s#%s) | | |\n", parent, page, slugs.slug(name))
		return
	}

	anchor := slugs.slug(relName(f.Path, scope))
	fmt.Fprintf(b, "| [`%s`](%s#%s) | %s | %s |\n",
		f.Path, page, anchor, f.Type, mdCell(mdDefaultCell(defaults, f)))
}

// mdDefaultCell is the table form of a key's default: backticked, and
// truncated when a long list would stretch the table unreadably.
func mdDefaultCell(defaults *Defaults, f *Field) string {
	d := defaults.Describe(f)
	if d == "" {
		return ""
	}
	if len(d) > mdDefaultMax {
		d = d[:mdDefaultMax] + "..."
	}
	return "`" + d + "`"
}

// mdCell makes a value safe inside a table cell.
func mdCell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}

// relName is a key's heading text: its path relative to the page's scope,
// so a page does not repeat its own prefix forty times. The full path stays
// one line up, in the at-a-glance table.
func relName(path, scope string) string {
	if scope != "" {
		if trimmed := strings.TrimPrefix(path, scope+"."); trimmed != path {
			return trimmed
		}
	}
	return path
}

// embeddedName is the heading for an embedded group under parent: relative
// to the page scope like any other key, except that a group whose parent is
// the scope itself keeps the parent's last segment, because a heading of
// bare "*" identifies nothing.
func embeddedName(parent, scope string) string {
	name := relName(parent, scope) + ".*"
	if name == "*" || strings.HasPrefix(name, ".") {
		if i := strings.LastIndex(parent, "."); i >= 0 {
			return parent[i+1:] + ".*"
		}
		return parent + ".*"
	}
	return name
}

// writeMDField emits one key, recursing into nested structs so that a
// nested group's keys stay on its section's page. A struct's own prose is
// kept under its heading -- the man page drops it, but a web page has the
// room, and the group comment is where shape-of-the-block prose lives.
// scope steers cross-reference rewriting (the section), page steers heading
// trimming (the page's own key prefix), and parent is the enclosing struct.
func writeMDField(b *strings.Builder, f *Field, defaults *Defaults, refs map[string]string, scope, page, parent string, slugs *slugger) {
	if f.IsStruct() {
		if len(f.Doc) > 0 && f.Path != "" {
			name := relName(f.Path, page)
			slugs.slug(name)
			fmt.Fprintf(b, "## `%s`\n\n", name)
			writeMDProse(b, f.Doc, refs, scope)
		}
		for _, c := range f.Children {
			writeMDField(b, c, defaults, refs, scope, page, f.Path, slugs)
		}
		return
	}

	// The embedded rotation options have no path of their own; they land in
	// the namespace of the struct that embeds them.
	if f.Embedded {
		name := embeddedName(parent, page)
		slugs.slug(name)
		fmt.Fprintf(b, "## `%s`\n\n", name)
		writeMDProse(b, f.Doc, refs, scope)
		return
	}

	name := relName(f.Path, page)
	slugs.slug(name)
	fmt.Fprintf(b, "## `%s`\n\n", name)
	line := fmt.Sprintf("`%s`", f.Type)
	if d := defaults.Describe(f); d != "" {
		line += fmt.Sprintf(", default `%s`", d)
	}
	b.WriteString(line + "\n\n")
	writeMDProse(b, f.Doc, refs, scope)
	if usage := mdUsage(f); usage != "" {
		b.WriteString("```yaml\n" + usage + "```\n\n")
	}
}

// mdEyebrow is the accent label above every generated page's heading, the
// app's PageHeading pattern (frontend/DESIGN.md) applied to the docs.
const mdEyebrow = "Configuration"

// writeMDFrontmatter emits the Starlight frontmatter plus the generated
// marker. Sidebar placement is not frontmatter's job here: the sidebar is
// declared wholesale by SidebarJSON, because Starlight's autogenerated
// sidebars sort directories ahead of files alphabetically, which loses the
// struct declaration order every other artifact preserves.
func writeMDFrontmatter(b *strings.Builder, title, description string) {
	b.WriteString("---\n")
	fmt.Fprintf(b, "title: %s\n", strconv.Quote(title))
	if description != "" {
		fmt.Fprintf(b, "description: %s\n", strconv.Quote(description))
	}
	fmt.Fprintf(b, "eyebrow: %s\n", strconv.Quote(mdEyebrow))
	b.WriteString("---\n\n")
	b.WriteString(mdGenerated + "\n\n")
}

// mdUsage renders a key in context: the YAML nesting it actually sits in,
// down to the key and a real value. "Where does this line go?" is the
// question a dotted path leaves open in a nested config file, and answering
// it per key is what keeps the reference from being a list of definitions.
//
// The value is the field's example: tag when it has one, otherwise its
// default: tag rendered exactly as defaults.yaml renders it -- so the
// snippet is always a line that parses, and always says something true.
// A key with neither is skipped: there is no honest value to show, and its
// doc comment usually carries its own example.
func mdUsage(f *Field) string {
	value := f.Example
	if value == "" {
		if !f.HasDefault {
			return ""
		}
		value = renderDefault(f)
	}
	if f.Path == "" {
		return ""
	}

	parts := strings.Split(f.Path, ".")
	var b strings.Builder
	for i, p := range parts[:len(parts)-1] {
		fmt.Fprintf(&b, "%s%s:\n", strings.Repeat("  ", i), p)
	}
	fmt.Fprintf(&b, "%s%s: %s\n", strings.Repeat("  ", len(parts)-1), parts[len(parts)-1], value)
	return b.String()
}

// sidebarItem is one Starlight sidebar entry: a page (Slug) or a group
// (Items). The JSON shape matches what starlight's sidebar config accepts,
// so user-docs/astro.config.mjs can read the file straight in.
type sidebarItem struct {
	Label string        `json:"label"`
	Slug  string        `json:"slug,omitempty"`
	Items []sidebarItem `json:"items,omitempty"`
}

// SidebarJSON renders the config reference's sidebar entries, in struct
// declaration order, as the JSON astro.config.mjs imports. A split section
// becomes a group holding its overview and subpages; a slug that stops
// existing fails the site build, so the sidebar cannot drift from the pages.
func SidebarJSON(sections []*Section) (string, error) {
	const prefix = "reference/config"
	items := []sidebarItem{{Label: "Overview", Slug: prefix}}
	for _, s := range sections {
		slug := prefix + "/" + strings.TrimSuffix(markdownFilename(s), ".md")
		split := splitChildren(s)
		if len(split) == 0 {
			items = append(items, sidebarItem{Label: markdownTitle(s), Slug: slug})
			continue
		}
		group := sidebarItem{
			Label: s.Key,
			Items: []sidebarItem{{Label: "Overview", Slug: slug}},
		}
		for _, c := range split {
			group.Items = append(group.Items, sidebarItem{Label: c.Key, Slug: slug + "/" + c.Key})
		}
		items = append(items, group)
	}

	out, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return "", fmt.Errorf("marshal sidebar: %w", err)
	}
	return string(out) + "\n", nil
}

// WriteSidebar writes the sidebar JSON, reporting whether it changed.
func WriteSidebar(path string, sections []*Section) (bool, error) {
	next, err := SidebarJSON(sections)
	if err != nil {
		return false, err
	}
	before, err := os.ReadFile(path)
	if err == nil && string(before) == next {
		return false, nil
	}
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("read %s: %w", path, err)
	}
	if err := os.WriteFile(path, []byte(next), 0o600); err != nil {
		return false, fmt.Errorf("write %s: %w", path, err)
	}
	return true, nil
}

// writeMDProse converts doc-comment lines into Markdown body text: Go field
// names rewritten to backticked config keys, blank lines kept as paragraph
// breaks, and indented example blocks fenced as YAML with their common
// indentation stripped.
func writeMDProse(b *strings.Builder, doc []string, refs map[string]string, scope string) {
	backtick := func(path string) string { return "`" + path + "`" }

	var example []string
	flushExample := func() {
		if len(example) == 0 {
			return
		}
		b.WriteString("```yaml\n")
		for _, l := range trimCommonIndent(example) {
			b.WriteString(l + "\n")
		}
		b.WriteString("```\n\n")
		example = nil
	}

	for _, line := range StripGoOnlyRefs(doc, refs) {
		switch {
		case strings.TrimSpace(line) == "":
			flushExample()
		case strings.HasPrefix(line, " ") || strings.HasPrefix(line, "\t"):
			example = append(example, line)
		default:
			flushExample()
			b.WriteString(mdEscape(rewriteRefsWith(line, refs, scope, backtick)) + "\n\n")
		}
	}
	flushExample()
}

// mdEscape neutralises raw HTML in prose: a doc comment writing
// {{.Extra.<name>}} means the literal angle brackets, but Markdown reads
// <name> as an inline HTML tag and swallows everything after it. Backtick
// code spans are left alone -- entities are not decoded inside them, so an
// escape there would show through as &lt;.
func mdEscape(line string) string {
	parts := strings.Split(line, "`")
	for i := 0; i < len(parts); i += 2 {
		parts[i] = strings.ReplaceAll(parts[i], "&", "&amp;")
		parts[i] = strings.ReplaceAll(parts[i], "<", "&lt;")
	}
	return strings.Join(parts, "`")
}

// trimCommonIndent strips the longest whitespace prefix shared by every line,
// so a doc-comment example keeps its internal nesting but starts at column
// zero inside the fence.
func trimCommonIndent(lines []string) []string {
	prefix := ""
	for i, l := range lines {
		indent := l[:len(l)-len(strings.TrimLeft(l, " \t"))]
		if i == 0 || strings.HasPrefix(prefix, indent) {
			prefix = indent
			continue
		}
		for !strings.HasPrefix(indent, prefix) {
			prefix = prefix[:len(prefix)-1]
		}
	}

	out := make([]string, 0, len(lines))
	for _, l := range lines {
		out = append(out, strings.TrimPrefix(l, prefix))
	}
	return out
}

// slugger produces the anchor Astro's own slugger (github-slugger) will give
// each heading, so table links land on the right entry. Lowercase, dots and
// other punctuation dropped, underscores kept, and a numeric suffix on
// repeats -- the same rules, applied in the same top-to-bottom order.
type slugger struct {
	seen map[string]int
}

func newSlugger() *slugger { return &slugger{seen: map[string]int{}} }

// slug registers the next heading and returns its anchor.
func (s *slugger) slug(heading string) string {
	base := make([]rune, 0, len(heading))
	for _, r := range strings.ToLower(heading) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '_', r == '-':
			base = append(base, r)
		case r == ' ':
			base = append(base, '-')
		}
	}
	out := string(base)
	n := s.seen[out]
	s.seen[out] = n + 1
	if n > 0 {
		return fmt.Sprintf("%s-%d", out, n)
	}
	return out
}

// WriteMarkdown renders the section pages into dir, creating it if needed,
// and removes any .md file beneath it that the walk no longer produces --
// the directory is wholly generated, so a leftover page is a section (or a
// split) that no longer exists. Reports whether anything changed.
func WriteMarkdown(dir string, sections []*Section, defaults *Defaults) (bool, error) {
	pages := MarkdownPages(sections, defaults)

	names := make([]string, 0, len(pages))
	for name := range pages {
		names = append(names, name)
	}
	sort.Strings(names)

	changed := false
	for _, name := range names {
		path := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return false, fmt.Errorf("create %s: %w", filepath.Dir(path), err)
		}
		before, err := os.ReadFile(path)
		if err == nil && string(before) == pages[name] {
			continue
		}
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return false, fmt.Errorf("read %s: %w", path, err)
		}
		if err := os.WriteFile(path, []byte(pages[name]), 0o600); err != nil {
			return false, fmt.Errorf("write %s: %w", path, err)
		}
		changed = true
	}

	removed, err := removeStalePages(dir, pages)
	if err != nil {
		return false, err
	}
	return changed || removed, nil
}

// removeStalePages deletes .md files under dir that no current page claims,
// then any directories that emptied out.
func removeStalePages(dir string, pages map[string]string) (bool, error) {
	stale, dirs, err := findStalePages(dir, pages)
	if err != nil {
		return false, err
	}

	for _, path := range stale {
		if err := os.Remove(path); err != nil {
			return false, fmt.Errorf("remove stale page %s: %w", path, err)
		}
	}

	// Deepest first, so a directory emptied by its child's removal goes too.
	sort.Sort(sort.Reverse(sort.StringSlice(dirs)))
	for _, d := range dirs {
		entries, err := os.ReadDir(d)
		if err != nil {
			return false, fmt.Errorf("read %s: %w", d, err)
		}
		if len(entries) > 0 {
			continue
		}
		if err := os.Remove(d); err != nil {
			return false, fmt.Errorf("remove empty dir %s: %w", d, err)
		}
	}
	return len(stale) > 0, nil
}

// findStalePages walks dir, returning the .md files no current page claims
// and every subdirectory found, both in walk order.
func findStalePages(dir string, pages map[string]string) (stale, dirs []string, err error) {
	err = filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if path != dir {
				dirs = append(dirs, path)
			}
			return nil
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		name := filepath.ToSlash(rel)
		if _, ok := pages[name]; !ok && strings.HasSuffix(name, ".md") {
			stale = append(stale, path)
		}
		return nil
	})
	if err != nil {
		return nil, nil, fmt.Errorf("walk %s: %w", dir, err)
	}
	return stale, dirs, nil
}
