
[request_definition]
r = sub, path, method

[policy_definition]
p = sub, path, method, eft

[role_definition]
g = _, _

[policy_effect]
# must have an allow and no deny statements that match
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub) && (keyGet2(r.path, p.path, "username") == r.sub || globMatch(r.path, p.path) || regexMatch(r.path, p.path)) && (p.method == '*' || regexMatch(r.method, p.method))